# Generated by Django 5.1.6 on 2025-03-15 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_remove_customuser_role_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('max_capacity', models.PositiveIntegerField(default=10)),
                ('booked_members', models.ManyToManyField(blank=True, related_name='booked_slots', to='users.customuser')),
                ('trainer', models.ForeignKey(limit_choices_to={'user_type': 'TRAINER'}, on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='end_after_start')],
            },
        ),
    ]
