# Generated by Django 5.1.7 on 2025-04-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_plan_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='description',
        ),
        migrations.AddField(
            model_name='plan',
            name='benefits',
            field=models.TextField(default='No benefits listed'),
        ),
        migrations.AddField(
            model_name='plan',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='duration_months',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plan',
            name='for_men',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='for_students',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='for_women',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('STD', 'Student'), ('REG', 'Regular'), ('PRM', 'Premium'), ('FAM', 'Family')], default='REG', max_length=3),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
