# Generated by Django 5.1.7 on 2025-04-25 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='fas fa-capsule', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='supplement',
            name='is_diet_food',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplement',
            name='weight_goal',
            field=models.CharField(blank=True, choices=[('gain', 'Weight Gain'), ('loss', 'Weight Loss'), ('maintain', 'Maintain')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productrecommendation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recommendations', to='supplements.supplement'),
        ),
        migrations.AlterField(
            model_name='productrecommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplement_recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supplement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='supplements/'),
        ),
        migrations.AlterUniqueTogether(
            name='productrecommendation',
            unique_together={('user', 'product', 'interaction_type')},
        ),
        migrations.AlterField(
            model_name='supplement',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplements.productcategory'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplements.producttype'),
        ),
        migrations.AddField(
            model_name='supplement',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplements.producttype'),
        ),
        migrations.DeleteModel(
            name='SupplementCategory',
        ),
    ]
